function addInfo(info){
    	if($("#mainCheck").is(':checked')){
			info.push("1");
		}else{
			info.push("0");
		}
    	if($("#systemCheck").is(':checked')){
			info.push("1");
		}else{
			info.push("0");
		}
    	if($("#employeeCheck").is(':checked')){
			info.push("1");
		}else{
			info.push("0");
		}
    	if($("#menuCheck").is(':checked')){
			info.push("1");
		}else{
			info.push("0");
		}
    	if($("#roomCheck").is(':checked')){
			info.push("1");
		}else{
			info.push("0");
		}
    	if($("#memberCheck").is(':checked')){
			info.push("1");
		}else{
			info.push("0");
		}
    	if($("#warehouseCheck").is(':checked')){
			info.push("1");
		}else{
			info.push("0");
		}
    	if($("#financeCheck").is(':checked')){
			info.push("1");
		}else{
			info.push("0");
		}
    	if($("#hotelCheck").is(':checked')){
			info.push("1");
		}else{
			info.push("0");
		}
    	return info;
    }


